[package]
name = "exonum_librocksdb-sys"
version = "0.5.1"
authors = ["Karl Hobley <karlhobley10@gmail.com>", "Arkadiy Paronyan <arkadiy@ethcore.io>", "The Exonum Team <exonum@bitfury.com>"]
license = "MIT/Apache-2.0/BSD-3-Clause"
description = "Native bindings to librocksdb"
readme = "README.md"
repository = "https://github.com/exonum/exonum_rocksdb.git"
keywords = [ "ffi", "rocksdb" ]

build = "build.rs"
links = "rocksdb"

[features]
default = [ "static" ]
static = []

[dependencies]
libc = "0.2"
tempdir = "0.3.5"

[dev-dependencies]
const-cstr = "0.2"

[build-dependencies]
gcc = { version = "0.3", features = ["parallel"] }
make-cmd = "0.1"
pkg-config = "0.3"
